version: '3'
services:
  hth.helix: 
    build: helix-team-hub
    hostname: hth
    domainname: helix
    env_file:
      - p4.env
    ports:
      - 4080:80
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tty: true
